Repository hashicorp/terraform-provider-tfe, pull requests merged in 2018-11, with the labels that each got.

#30 Fix a bug that prevented to set auto-apply to false
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
Labels: size/XS

#32 Tidy up docs and error messages for compound import IDs
  tfe/resource_tfe_sentinel_policy.go
  tfe/resource_tfe_team.go
  tfe/resource_tfe_team_access.go
  tfe/resource_tfe_team_member.go
  tfe/resource_tfe_variable.go
  tfe/resource_tfe_workspace.go
  website/docs/r/organization.html.markdown
  website/docs/r/organization_token.html.markdown
  website/docs/r/sentinel_policy.html.markdown
  website/docs/r/team.html.markdown
  website/docs/r/team_access.html.markdown
  website/docs/r/team_member.html.markdown
  website/docs/r/team_members.html.markdown
  website/docs/r/team_token.html.markdown
  website/docs/r/variable.html.markdown
  website/docs/r/workspace.html.markdown
Labels: size/M

#33 Add support for Sentinel policy sets
  tfe/provider.go
  tfe/resource_tfe_policy_set.go
  tfe/resource_tfe_policy_set_test.go
  tfe/resource_tfe_sentinel_policy.go
  tfe/resource_tfe_sentinel_policy_test.go
  vendor/github.com/hashicorp/go-tfe/README.md
  vendor/github.com/hashicorp/go-tfe/apply.go
  vendor/github.com/hashicorp/go-tfe/logreader.go
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/plan.go
  vendor/github.com/hashicorp/go-tfe/policy.go
  vendor/github.com/hashicorp/go-tfe/policy_check.go
  vendor/github.com/hashicorp/go-tfe/policy_set.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/vendor.json
  website/docs/r/policy_set.html.markdown
  website/docs/r/sentinel_policy.html.markdown
  website/tfe.erb
Labels: size/XXL

#34 govendor: update `go-tfe`
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-tfe/apply.go
  vendor/github.com/hashicorp/go-tfe/configuration_version.go
  vendor/github.com/hashicorp/go-tfe/go.mod
  vendor/github.com/hashicorp/go-tfe/go.sum
  vendor/github.com/hashicorp/go-tfe/logreader.go
  vendor/github.com/hashicorp/go-tfe/oauth_client.go
  vendor/github.com/hashicorp/go-tfe/oauth_token.go
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/organization_token.go
  vendor/github.com/hashicorp/go-tfe/plan.go
  vendor/github.com/hashicorp/go-tfe/policy.go
  vendor/github.com/hashicorp/go-tfe/policy_check.go
  vendor/github.com/hashicorp/go-tfe/policy_set.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/ssh_key.go
  vendor/github.com/hashicorp/go-tfe/state_version.go
  vendor/github.com/hashicorp/go-tfe/team.go
  vendor/github.com/hashicorp/go-tfe/team_access.go
  vendor/github.com/hashicorp/go-tfe/team_member.go
  vendor/github.com/hashicorp/go-tfe/team_token.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/variable.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/golang.org/x/time/LICENSE
  vendor/golang.org/x/time/PATENTS
  vendor/golang.org/x/time/rate/rate.go
  vendor/vendor.json
Labels: size/XXL

#35 Make switching global on/off a bit cleaner
  tfe/resource_tfe_policy_set.go
  tfe/resource_tfe_policy_set_test.go
  tfe/resource_tfe_sentinel_policy.go
  vendor/github.com/hashicorp/go-tfe/go.mod
  vendor/github.com/hashicorp/go-tfe/go.sum
  vendor/github.com/hashicorp/go-tfe/logreader.go
  vendor/github.com/hashicorp/go-tfe/policy_set.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/vendor.json
Labels: size/M

#36 Fixup the policy set docs
  website/docs/r/policy_set.html.markdown
  website/docs/r/sentinel_policy.html.markdown
Labels: size/XS

#38 r/tfe_workspace: support assigning an SSH key
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
  website/docs/r/workspace.html.markdown
Labels: size/L
