Repository hashicorp/terraform-provider-tfe, pull requests merged in 2019-02, with the labels that each got.

#58 Update description to not be on a bullet point
  website/docs/r/workspace.html.markdown
Labels: documentation, size/XS

#57 website: some stuff about workspace IDs
  website/docs/d/workspace.html.markdown
  website/docs/d/workspace_ids.html.markdown
  website/docs/r/policy_set.html.markdown
  website/docs/r/team_access.html.markdown
  website/docs/r/variable.html.markdown
  website/docs/r/workspace.html.markdown
Labels: documentation, size/M

#59 vendor: github.com/hashicorp/go-tfe@v0.3.8
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/modules.txt
Labels: dependencies, size/XS

#60 vendor: github.com/hashicorp/terraform@ee1f8f9
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform/config/module/storage.go
  vendor/github.com/hashicorp/terraform/svchost/disco/disco.go
  vendor/github.com/hashicorp/terraform/svchost/disco/host.go
  vendor/github.com/hashicorp/terraform/version/version.go
  vendor/github.com/jmespath/go-jmespath/.gitignore
  vendor/modules.txt
Labels: dependencies, size/L

#55 provider: Enable request/response logging
  tfe/provider.go
Labels: size/XS

#62 goenv: Pin Go version to 1.11.5
  .go-version
Labels: dependencies, size/XS

#61 Report detailed version constraints info
  tfe/provider.go
  tfe/provider_test.go
  version/version.go
Labels: size/L

#64 Add a check when migrating vcs_repo from a set to a list
  CHANGELOG.md
  tfe/resource_tfe_workspace.go
Labels: size/XS

#66 test: Expose TFE_MEMBER_USERNAME & TFE_MEMBER_SECOND_USERNAME
  tfe/provider_test.go
  tfe/resource_tfe_team_members_test.go
Labels: size/M

#67 Add owners_team_saml_role_id organization option
  go.mod
  go.sum
  tfe/resource_tfe_organization.go
  tfe/resource_tfe_organization_test.go
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/modules.txt
  website/docs/r/organization.html.markdown
Labels: dependencies, documentation, size/M
