Repository hashicorp/terraform-provider-tfe, pull requests merged in 2019-06, with the labels that each got.

#78 Add support for TFE_HOSTNAME and TFE_TOKEN environment variables
  README.md
  tfe/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#77 Add monorepo filtering workspace config fields
  GNUmakefile
  go.mod
  go.sum
  tfe/data_source_workspace.go
  tfe/data_source_workspace_test.go
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
  vendor/github.com/hashicorp/go-tfe/cost_estimation.go
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/plan.go
  vendor/github.com/hashicorp/go-tfe/plan_export.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/type_helpers.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/modules.txt
  website/docs/d/workspace.html.markdown
  website/docs/r/workspace.html.markdown
Labels: dependencies, documentation, size/XL

#80 [WIP] r/policy_set: add support for VCS policy sets
  README.md
  go.mod
  go.sum
  tfe/provider_test.go
  tfe/resource_tfe_oauth_client_test.go
  tfe/resource_tfe_policy_set.go
  tfe/resource_tfe_policy_set_test.go
  tfe/resource_tfe_team_members_test.go
  vendor/github.com/hashicorp/go-tfe/README.md
  vendor/github.com/hashicorp/go-tfe/policy_set.go
  vendor/modules.txt
  website/docs/r/policy_set.html.markdown
Labels: dependencies, documentation, enhancement, size/XL

#81 Ensure that changes are applied for monorepos
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
Labels: size/S
