Repository hashicorp/terraform-provider-tfe, pull requests merged in 2019-01, with the labels that each got.

#42 Add support for managing OAuth Clients
  tfe/provider.go
  tfe/provider_test.go
  tfe/resource_tfe_oauth_client.go
  tfe/resource_tfe_oauth_client_test.go
  website/docs/r/oauth_client.html.markdown
  website/docs/r/policy_set.html.markdown
  website/docs/r/sentinel_policy.html.markdown
  website/docs/r/ssh_key.html.markdown
  website/docs/r/variable.html.markdown
  website/docs/r/workspace.html.markdown
  website/tfe.erb
Labels: documentation, new-resource, size/XL

#46 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  tfe/data_source_ssh_key.go
  tfe/data_source_ssh_key_test.go
  tfe/data_source_team.go
  tfe/data_source_team_access.go
  tfe/data_source_team_access_test.go
  tfe/data_source_team_test.go
  tfe/data_source_workspace.go
  tfe/data_source_workspace_ids.go
  tfe/data_source_workspace_ids_test.go
  tfe/data_source_workspace_test.go
  tfe/provider.go
  tfe/resource_tfe_oauth_client.go
  tfe/resource_tfe_oauth_client_test.go
  tfe/resource_tfe_organization.go
  tfe/resource_tfe_organization_test.go
  tfe/resource_tfe_organization_token.go
  tfe/resource_tfe_organization_token_test.go
  tfe/resource_tfe_policy_set.go
  tfe/resource_tfe_policy_set_test.go
  tfe/resource_tfe_sentinel_policy.go
  tfe/resource_tfe_sentinel_policy_test.go
  tfe/resource_tfe_ssh_key.go
  tfe/resource_tfe_ssh_key_test.go
  tfe/resource_tfe_team.go
  tfe/resource_tfe_team_access.go
  tfe/resource_tfe_team_access_test.go
  tfe/resource_tfe_team_member.go
  tfe/resource_tfe_team_member_test.go
  tfe/resource_tfe_team_members.go
  tfe/resource_tfe_team_members_test.go
  tfe/resource_tfe_team_test.go
  tfe/resource_tfe_team_token.go
  tfe/resource_tfe_team_token_test.go
  tfe/resource_tfe_variable.go
  tfe/resource_tfe_variable_test.go
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
Labels: size/XL

#47 Fixup documentation a little
  website/docs/d/workspace.html.markdown
  website/docs/d/workspace_ids.html.markdown
Labels: documentation, size/XS

#50 govendor: update dependencies
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/go.sum
  vendor/github.com/hashicorp/go-tfe/go.mod
  vendor/github.com/hashicorp/go-tfe/go.sum
  vendor/github.com/hashicorp/go-tfe/team_access.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/vendor.json
Labels: dependencies, size/S

#49 add 'plan' access level to tfe_team_access resource
  tfe/resource_tfe_team_access.go
  website/docs/r/team_access.html.markdown
Labels: dependencies, documentation, size/XS

#51 Try to find a workspace by external ID before removing it
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
Labels: enhancement, size/M

#53 User a list instead of a set for a workspace vcs_repo
  tfe/resource_tfe_workspace.go
Labels: size/XS

#54 govendor: update dependencies
  vendor/github.com/hashicorp/go-tfe/configuration_version.go
  vendor/github.com/hashicorp/go-tfe/team.go
  vendor/vendor.json
Labels: dependencies, size/M
