Repository hashicorp/terraform-provider-tfe, pull requests merged in 2019-12, with the labels that each got.

#109 Retry server errors
  tfe/provider.go
Labels: size/XS

#99 Add Azure DevOps Server and Azure DevOps Services as valid OAuth client service providers
  go.mod
  go.sum
  tfe/resource_tfe_oauth_client.go
  website/docs/r/oauth_client.html.markdown
Labels: documentation, size/S

#110 update vendor
  vendor/github.com/hashicorp/go-slug/README.md
  vendor/github.com/hashicorp/go-slug/slug.go
  vendor/github.com/hashicorp/go-slug/terraformignore.go
  vendor/github.com/hashicorp/go-tfe/README.md
  vendor/github.com/hashicorp/go-tfe/go.mod
  vendor/github.com/hashicorp/go-tfe/go.sum
  vendor/github.com/hashicorp/go-tfe/oauth_client.go
  vendor/modules.txt
Labels: dependencies, size/XL

#113 BUGFIX: Use isValidString not nil check for private_key
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/oauth_client.go
  vendor/modules.txt
Labels: dependencies, size/XS
