Repository hashicorp/terraform-provider-tfe, pull requests merged in 2020-06, with the labels that each got.

#182 Deprecate workspace_external_id/workspace_external_ids in tfe_notification_configuration, tfe_policy_set, and tfe_run_trigger resources
  CHANGELOG.md
  go.mod
  go.sum
  tfe/data_source_workspace_ids.go
  tfe/data_source_workspace_ids_test.go
  tfe/resource_tfe_notification_configuration.go
  tfe/resource_tfe_notification_configuration_test.go
  tfe/resource_tfe_policy_set.go
  tfe/resource_tfe_policy_set_test.go
  tfe/resource_tfe_run_trigger.go
  tfe/resource_tfe_run_trigger_test.go
  tfe/resource_tfe_workspace.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/go-tfe/README.md
  vendor/github.com/hashicorp/go-tfe/cost_estimate.go
  vendor/github.com/hashicorp/go-tfe/notification_configuration.go
  vendor/github.com/hashicorp/go-tfe/policy_set.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/compose.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/computed.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/condition.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/doc.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/force_new.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/validate.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/d/workspace_ids.html.markdown
  website/docs/r/notification_configuration.html.markdown
  website/docs/r/policy_set.html.markdown
  website/docs/r/run_trigger.html.markdown
Labels: dependencies, deprecation, documentation, size/XXL

#172 Providing guidance on tfe_workspace operations
  website/docs/d/workspace.html.markdown
Labels: documentation, size/XS

#167 Update workspace.html.markdown
  website/docs/r/workspace.html.markdown
Labels: documentation, size/XS

#166 Fix missing quote
  website/docs/r/team_organization_member.html.markdown
Labels: documentation, size/XS

#185 Updated the resourceTFEPolicySetUpdate function
  CHANGELOG.md
  tfe/resource_tfe_policy_set.go
  tfe/resource_tfe_policy_set_test.go
Labels: bug, size/M

#186 Docs: Fix tfe_resource_team's block argument
  website/docs/r/team.html.markdown
Labels: documentation, size/XS

#184 tfe_team_access: Add Custom workspace access support
  CHANGELOG.md
  go.mod
  go.sum
  tfe/data_source_team_access.go
  tfe/data_source_team_access_test.go
  tfe/resource_tfe_team_access.go
  tfe/resource_tfe_team_access_test.go
  vendor/github.com/hashicorp/go-tfe/team_access.go
  vendor/github.com/hashicorp/go-tfe/type_helpers.go
  vendor/modules.txt
  website/docs/d/team_access.html.markdown
  website/docs/r/team_access.html.markdown
Labels: dependencies, documentation, enhancement, size/XL
