Repository hashicorp/terraform-provider-tfe, pull requests merged in 2020-04, with the labels that each got.

#156 docs: update import ID for tfe_workspace
  website/docs/r/workspace.html.markdown
Labels: documentation, size/XS

#159 Update docs to reflect changes to workspace IDs + fix broken code block
  website/docs/d/workspace_ids.html.markdown
  website/docs/index.html.markdown
  website/docs/r/workspace.html.markdown
Labels: documentation, size/XS

#154 Use org memberships for teams
  .circleci/config.yml
  CHANGELOG.md
  go.mod
  go.sum
  tfe/provider.go
  tfe/resource_tfe_organization_membership.go
  tfe/resource_tfe_organization_membership_test.go
  tfe/resource_tfe_team_organization_member.go
  tfe/resource_tfe_team_organization_member_test.go
  vendor/github.com/hashicorp/go-tfe/go.mod
  vendor/github.com/hashicorp/go-tfe/organization_membership.go
  vendor/github.com/hashicorp/go-tfe/team.go
  vendor/github.com/hashicorp/go-tfe/team_member.go
  vendor/github.com/hashicorp/go-tfe/testing.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/modules.txt
  website/docs/r/organization_membership.html.markdown
  website/docs/r/team_member.html.markdown
  website/docs/r/team_members.html.markdown
  website/docs/r/team_organization_member.html.markdown
  website/tfe.erb
Labels: dependencies, documentation, size/XL

#162 Fix workspace panic
  CHANGELOG.md
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
Labels: bug, crash, size/M
