Repository hashicorp/terraform-provider-tfe, pull requests merged in 2020-03, with the labels that each got.

#137 Workspace working directory updates
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
Labels: size/M

#138 Reset trigger prefixes for workspace resources when removed from the config
  CHANGELOG.md
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
Labels: size/M

#143 Remove beta flag from tfe_run_trigger resource documentation
  website/docs/r/run_trigger.html.markdown
Labels: documentation, size/XS

#106 Workspace id migration
  CHANGELOG.md
  tfe/client_mock.go
  tfe/data_source_team_access.go
  tfe/data_source_workspace.go
  tfe/data_source_workspace_test.go
  tfe/resource_tfe_team_access.go
  tfe/resource_tfe_team_access_migrate.go
  tfe/resource_tfe_team_access_migrate_test.go
  tfe/resource_tfe_variable.go
  tfe/resource_tfe_variable_migrate.go
  tfe/resource_tfe_variable_migrate_test.go
  tfe/resource_tfe_variable_test.go
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_migrate.go
  tfe/resource_tfe_workspace_migrate_test.go
  tfe/resource_tfe_workspace_test.go
  tfe/testing.go
  tfe/workspace_helpers.go
  tfe/workspace_helpers_test.go
  website/docs/d/workspace.html.markdown
  website/docs/d/workspace_ids.html.markdown
  website/docs/r/team_access.html.markdown
  website/docs/r/variable.html.markdown
  website/docs/r/workspace.html.markdown
Labels: documentation, size/XXL

#148 Add documentation on constraining provider versions
  README.md
  website/docs/index.html.markdown
Labels: documentation, size/M
