Repository hashicorp/terraform-provider-tfe, pull requests merged in 2020-09, with the labels that each got.

#178 run_trigger: retry when a "locked" error is returned
  tfe/resource_tfe_run_trigger.go
  tfe/resource_tfe_run_trigger_test.go
Labels: size/M

#218 Ko run triggers retry
  tfe/resource_tfe_run_trigger.go
  tfe/resource_tfe_run_trigger_test.go
Labels: size/M

#222 [tfe_registry_module] Docs: Remove errant 's' from resource name
  website/docs/r/registry_module.html.markdown
Labels: documentation, size/XS

#212 New datasource: tfe_oauth_client
  CHANGELOG.md
  tfe/data_source_oauth_client.go
  tfe/data_source_oauth_client_test.go
  tfe/provider.go
  website/docs/d/oauth_client.html.markdown
  website/tfe.erb
Labels: documentation, size/L

#210 Add speculative_enabled argument to tfe_workspace
  go.mod
  go.sum
  tfe/data_source_workspace.go
  tfe/data_source_workspace_test.go
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
  vendor/github.com/hashicorp/go-tfe/README.md
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/modules.txt
  website/docs/d/workspace.html.markdown
  website/docs/r/workspace.html.markdown
Labels: dependencies, documentation, size/L

#223 Fix type conversion bug
  tfe/resource_tfe_workspace.go
Labels: size/XS

#215 Check if module has been imported
  tfe/resource_tfe_registry_module.go
Labels: size/XS

#220 Import branch
  tfe/resource_tfe_workspace.go
  tfe/resource_tfe_workspace_test.go
Labels: size/S

#217 Fixed not being able to get VCS branch name when importing workspace
  tfe/resource_tfe_workspace.go
Labels: size/XS
