Repository hashicorp/terraform-provider-tfe, pull requests merged in 2020-07, with the labels that each got.

#191 Add support for registry modules, destination type of email in notification configurations, and data source + import for organization memberships
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  tfe/data_source_organization_membership.go
  tfe/data_source_organization_membership_test.go
  tfe/provider.go
  tfe/provider_test.go
  tfe/resource_tfe_notification_configuration.go
  tfe/resource_tfe_notification_configuration_test.go
  tfe/resource_tfe_organization_membership.go
  tfe/resource_tfe_organization_membership_test.go
  tfe/resource_tfe_registry_module.go
  tfe/resource_tfe_registry_module_test.go
  vendor/github.com/hashicorp/go-tfe/README.md
  vendor/github.com/hashicorp/go-tfe/notification_configuration.go
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/registry_module.go
  vendor/github.com/hashicorp/go-tfe/team.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/modules.txt
  website/docs/d/organization_membership.html.markdown
  website/docs/r/notification_configuration.html.markdown
  website/docs/r/oauth_client.html.markdown
  website/docs/r/organization_membership.html.markdown
  website/docs/r/registry_module.html.markdown
  website/docs/r/run_trigger.html.markdown
Labels: dependencies, documentation, enhancement, new-data-source, new-resource, size/XXL

#192 Fix broken Travis CI tests
  tfe/resource_tfe_registry_module_test.go
Labels: size/XS

#197 fix missing sidebar links
  website/tfe.erb
Labels: documentation, size/XS
